spring:
    data:
        mongodb:
            host: ds125126.mlab.com
            port: 25126
            database: territory-war
            username: territory-war
            password: territory-war
    redis:
        host: 52.39.167.134
        port: 6379
        #password: